assessmentDirName: _assessment-data
logDirName: _logs
logFileName: data-send-and-save-log.log
varsFile: '/var/www/private/staging.yml'
notificationEmailRecipients:
  - product@brainfx.com
  - support@brainfx.com
dbConf:
  database: staging.admin.brainfx.com
  host: localhost
  port: 3306
  driver: mysql
  prefix: ''
