assessmentDirName: _assessment-data
logDirName: _logs
logFileName: data-send-and-save-log.log
varsFile: '/var/www/pse/production'
notificationEmailRecipients:
  - support@brainfx.com
dbConf:
  database: 'abc'
  host: 10.1.2.2
  port: 2222
  driver: mysql
  prefix: ''
